package br.gilson.view;

import br.gilson.controller.AutoTyper;
import br.gilson.model.Task;
import br.gilson.model.TaskConfig;
import br.gilson.model.TaskFactory;
import de.ksquared.system.keyboard.GlobalKeyListener;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Gilson da Silva
 * @version 1.0
 */
public class PrincipalForm extends javax.swing.JFrame implements KeyListener,
        ContainerListener {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initGlobalListener();
        setTitle("Auto Typer");
        addKeyListener(this);
        initComponents();
        //Desativa o atalho da tecla F10, evitando o bug das mensagens.
        jMenuBar1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("F10"), "none");
        setResizable(false);

        initTaskConfig();
        //Ajusta o frame no centro da tela
        tela = Toolkit.getDefaultToolkit().getScreenSize();
        tamanhoFrame = getSize();
        setBounds((tela.width / 2) - (tamanhoFrame.width / 2),
                (tela.height / 2) - (tamanhoFrame.height / 2),
                tamanhoFrame.width, tamanhoFrame.height);

        //Listener
        addKeyAndContainerListenerRecursively(this);
    }

    private void initTaskConfig() {
        taskConfigs = new TaskConfig[12];
        taskConfigs[0] = new TaskConfig(jCheckBoxF1, jTextFieldIniciarEmF1, jTextFieldDelayF1);
        taskConfigs[1] = new TaskConfig(jCheckBoxF2, jTextFieldIniciarEmF2, jTextFieldDelayF2);
        taskConfigs[2] = new TaskConfig(jCheckBoxF3, jTextFieldIniciarEmF3, jTextFieldDelayF3);
        taskConfigs[3] = new TaskConfig(jCheckBoxF4, jTextFieldIniciarEmF4, jTextFieldDelayF4);
        taskConfigs[4] = new TaskConfig(jCheckBoxF5, jTextFieldIniciarEmF5, jTextFieldDelayF5);
        taskConfigs[5] = new TaskConfig(jCheckBoxF6, jTextFieldIniciarEmF6, jTextFieldDelayF6);
        taskConfigs[6] = new TaskConfig(jCheckBoxF7, jTextFieldIniciarEmF7, jTextFieldDelayF7);
        taskConfigs[7] = new TaskConfig(jCheckBoxF8, jTextFieldIniciarEmF8, jTextFieldDelayF8);
        taskConfigs[8] = new TaskConfig(jCheckBoxF9, jTextFieldIniciarEmF9, jTextFieldDelayF9);
        taskConfigs[9] = new TaskConfig(jCheckBoxF10, jTextFieldIniciarEmF10, jTextFieldDelayF10);
        taskConfigs[10] = new TaskConfig(jCheckBoxF11, jTextFieldIniciarEmF11, jTextFieldDelayF11);
        taskConfigs[11] = new TaskConfig(jCheckBoxF12, jTextFieldIniciarEmF12, jTextFieldDelayF12);
    }

    //Adiciona um listener global
    private void addKeyAndContainerListenerRecursively(Component c) {
        try {
            c.addKeyListener(this);
            if (c instanceof Container) {
                Container cont = (Container) c;
                cont.addContainerListener((ContainerListener) this);
                Component[] children = cont.getComponents();
                for (Component children1 : children) {
                    addKeyAndContainerListenerRecursively(children1);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonIniciar = new javax.swing.JToggleButton();
        jButtonLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxF1 = new javax.swing.JCheckBox();
        jCheckBoxF2 = new javax.swing.JCheckBox();
        jCheckBoxF3 = new javax.swing.JCheckBox();
        jCheckBoxF4 = new javax.swing.JCheckBox();
        jCheckBoxF5 = new javax.swing.JCheckBox();
        jCheckBoxF6 = new javax.swing.JCheckBox();
        jCheckBoxF7 = new javax.swing.JCheckBox();
        jCheckBoxF8 = new javax.swing.JCheckBox();
        jCheckBoxF9 = new javax.swing.JCheckBox();
        jCheckBoxF10 = new javax.swing.JCheckBox();
        jCheckBoxF11 = new javax.swing.JCheckBox();
        jCheckBoxF12 = new javax.swing.JCheckBox();
        jTextFieldIniciarEmF1 = new javax.swing.JTextField();
        jTextFieldIniciarEmF2 = new javax.swing.JTextField();
        jTextFieldIniciarEmF3 = new javax.swing.JTextField();
        jTextFieldIniciarEmF4 = new javax.swing.JTextField();
        jTextFieldIniciarEmF5 = new javax.swing.JTextField();
        jTextFieldIniciarEmF6 = new javax.swing.JTextField();
        jTextFieldIniciarEmF7 = new javax.swing.JTextField();
        jTextFieldIniciarEmF8 = new javax.swing.JTextField();
        jTextFieldIniciarEmF9 = new javax.swing.JTextField();
        jTextFieldIniciarEmF10 = new javax.swing.JTextField();
        jTextFieldIniciarEmF11 = new javax.swing.JTextField();
        jTextFieldIniciarEmF12 = new javax.swing.JTextField();
        jTextFieldDelayF1 = new javax.swing.JTextField();
        jTextFieldDelayF2 = new javax.swing.JTextField();
        jTextFieldDelayF3 = new javax.swing.JTextField();
        jTextFieldDelayF4 = new javax.swing.JTextField();
        jTextFieldDelayF5 = new javax.swing.JTextField();
        jTextFieldDelayF6 = new javax.swing.JTextField();
        jTextFieldDelayF7 = new javax.swing.JTextField();
        jTextFieldDelayF8 = new javax.swing.JTextField();
        jTextFieldDelayF9 = new javax.swing.JTextField();
        jTextFieldDelayF10 = new javax.swing.JTextField();
        jTextFieldDelayF11 = new javax.swing.JTextField();
        jTextFieldDelayF12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAutoTyper = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButtonIniciar.setText("Iniciar");
        jToggleButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonIniciarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jCheckBoxF1.setText("F1");

        jCheckBoxF2.setText("F2");

        jCheckBoxF3.setText("F3");

        jCheckBoxF4.setText("F4");

        jCheckBoxF5.setText("F5");

        jCheckBoxF6.setText("F6");

        jCheckBoxF7.setText("F7");

        jCheckBoxF8.setText("F8");

        jCheckBoxF9.setText("F9");

        jCheckBoxF10.setText("F10");

        jCheckBoxF11.setText("F11");

        jCheckBoxF12.setText("F12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIniciarEmF1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIniciarEmF2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIniciarEmF3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIniciarEmF4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIniciarEmF12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIniciarEmF10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIniciarEmF11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxF5)
                            .addComponent(jCheckBoxF6)
                            .addComponent(jCheckBoxF7)
                            .addComponent(jCheckBoxF8)
                            .addComponent(jCheckBoxF9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIniciarEmF5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIniciarEmF6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIniciarEmF7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIniciarEmF8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIniciarEmF9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDelayF1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldDelayF12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldDelayF10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldDelayF11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDelayF5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDelayF9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF1)
                    .addComponent(jTextFieldIniciarEmF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF2)
                    .addComponent(jTextFieldIniciarEmF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF3)
                    .addComponent(jTextFieldIniciarEmF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF4)
                    .addComponent(jTextFieldIniciarEmF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxF6)
                            .addComponent(jTextFieldIniciarEmF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxF7)
                            .addComponent(jTextFieldIniciarEmF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxF8)
                            .addComponent(jTextFieldIniciarEmF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxF9)
                            .addComponent(jTextFieldIniciarEmF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldIniciarEmF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF10)
                    .addComponent(jTextFieldIniciarEmF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF11)
                    .addComponent(jTextFieldIniciarEmF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxF12)
                    .addComponent(jTextFieldIniciarEmF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextFieldDelayF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDelayF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDelayF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDelayF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldDelayF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDelayF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDelayF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDelayF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDelayF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDelayF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDelayF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDelayF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Iniciar Em");

        jLabel2.setText("Delay");

        jMenuAutoTyper.setText("AutoTyper");
        jMenuAutoTyper.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAutoTyperMenuSelected(evt);
            }
        });

        jMenuItemAjuda.setText("Ajuda");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenuAutoTyper.add(jMenuItemAjuda);

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAutoTyper.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAutoTyper);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jToggleButtonIniciar)
                                .addGap(139, 139, 139)
                                .addComponent(jButtonLimpar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonIniciar)
                    .addComponent(jButtonLimpar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initGlobalListener() {
        new GlobalKeyListener().addKeyListener(new de.ksquared.system.keyboard.KeyAdapter() {
            @Override
            public void keyPressed(de.ksquared.system.keyboard.KeyEvent event) {

            }

            @Override
            public void keyReleased(de.ksquared.system.keyboard.KeyEvent event) {
                //Tecla home
                if (event.getVirtualKeyCode() == de.ksquared.system.keyboard.KeyEvent.VK_HOME) {
                    jToggleButtonIniciar.doClick();
                }
            }
        });
    }

    //TODO
    /*public void disableCheckBoxes() {
     for (JCheckBox checkBox : checkBoxes) {
     checkBox.setEnabled(false);
     }
     }
    
     public void enableCheckBoxes() {
     for (JCheckBox checkBox : checkBoxes) {
     checkBox.setEnabled(true);
     }
     }*/
    private void atualizarTaskConfig() {

    }
    private void jToggleButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonIniciarActionPerformed

        this.jToggleButtonIniciar.setFocusable(false);
        if (this.jToggleButtonIniciar.isSelected()) {
            //disableCheckBoxes();
            this.jToggleButtonIniciar.setText("Parar ");
            //Verifica quais boxes estão tickadas
            Task[] tasks = new Task[12];
            int i = 0;
            for (TaskConfig taskConfig : taskConfigs) {
                if (taskConfig.isValid()) {
                    tasks[i++] = TaskFactory.getTask(taskConfig);
                }
            }
            /*for (JCheckBox checkBoxe : checkBoxes) {
             if (checkBoxe.isSelected()) {
             checadas.add(checkBoxe.getText());
             }
             }*/
            //Verifica se os valores inseridos são positivos
            /*if (delay < 0) {
             JOptionPane.showMessageDialog(this, "Por favor, insira valores acima de 0");
             return;
             }*/
            //Inicia o auto-typer das teclas selecionadas
            AutoTyper.start(tasks);
        } else {
            this.jToggleButtonIniciar.setText("Iniciar");
            AutoTyper.stop();
            //enableCheckBoxes();
        }
    }//GEN-LAST:event_jToggleButtonIniciarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jMenuAutoTyperMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAutoTyperMenuSelected

    }//GEN-LAST:event_jMenuAutoTyperMenuSelected

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        AjudaDialog ajuda = new AjudaDialog(this, rootPaneCheckingEnabled);
        Dimension tamanhoDialog = ajuda.getSize();
        ajuda.setBounds(((tela.width / 2) - (tamanhoDialog.width / 2)) + 50,
                (tela.height / 2) - (tamanhoDialog.height / 2),
                tamanhoDialog.width, tamanhoDialog.height);
        ajuda.setResizable(false);
        ajuda.setVisible(true);
    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        SobreDialog sobre = new SobreDialog(this, rootPaneCheckingEnabled);
        Dimension tamanhoDialog = sobre.getSize();
        sobre.setBounds(((tela.width / 2) - (tamanhoDialog.width / 2)) + 50,
                (tela.height / 2) - (tamanhoDialog.height / 2),
                tamanhoDialog.width, tamanhoDialog.height);
        sobre.setResizable(false);
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed
    private void limpar() {
        //TODO
        /*for (JCheckBox checkBox : checkBoxes) {
         checkBox.setSelected(false);
         this.jTextFieldDelay.setText("");
         }*/
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);

            }
        });
    }
    private Dimension tamanhoFrame;
    private Dimension tela;
    private TaskConfig[] taskConfigs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JCheckBox jCheckBoxF1;
    private javax.swing.JCheckBox jCheckBoxF10;
    private javax.swing.JCheckBox jCheckBoxF11;
    private javax.swing.JCheckBox jCheckBoxF12;
    private javax.swing.JCheckBox jCheckBoxF2;
    private javax.swing.JCheckBox jCheckBoxF3;
    private javax.swing.JCheckBox jCheckBoxF4;
    private javax.swing.JCheckBox jCheckBoxF5;
    private javax.swing.JCheckBox jCheckBoxF6;
    private javax.swing.JCheckBox jCheckBoxF7;
    private javax.swing.JCheckBox jCheckBoxF8;
    private javax.swing.JCheckBox jCheckBoxF9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAutoTyper;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDelayF1;
    private javax.swing.JTextField jTextFieldDelayF10;
    private javax.swing.JTextField jTextFieldDelayF11;
    private javax.swing.JTextField jTextFieldDelayF12;
    private javax.swing.JTextField jTextFieldDelayF2;
    private javax.swing.JTextField jTextFieldDelayF3;
    private javax.swing.JTextField jTextFieldDelayF4;
    private javax.swing.JTextField jTextFieldDelayF5;
    private javax.swing.JTextField jTextFieldDelayF6;
    private javax.swing.JTextField jTextFieldDelayF7;
    private javax.swing.JTextField jTextFieldDelayF8;
    private javax.swing.JTextField jTextFieldDelayF9;
    private javax.swing.JTextField jTextFieldIniciarEmF1;
    private javax.swing.JTextField jTextFieldIniciarEmF10;
    private javax.swing.JTextField jTextFieldIniciarEmF11;
    private javax.swing.JTextField jTextFieldIniciarEmF12;
    private javax.swing.JTextField jTextFieldIniciarEmF2;
    private javax.swing.JTextField jTextFieldIniciarEmF3;
    private javax.swing.JTextField jTextFieldIniciarEmF4;
    private javax.swing.JTextField jTextFieldIniciarEmF5;
    private javax.swing.JTextField jTextFieldIniciarEmF6;
    private javax.swing.JTextField jTextFieldIniciarEmF7;
    private javax.swing.JTextField jTextFieldIniciarEmF8;
    private javax.swing.JTextField jTextFieldIniciarEmF9;
    private javax.swing.JToggleButton jToggleButtonIniciar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        //Atalho para selecionar as teclas (somente se o botão iniciar
        //estiver desativado
        if (!this.jToggleButtonIniciar.isSelected()) {
            int code = e.getKeyCode();
            switch (code) {
                //F1
                case 112:
                    if (this.jCheckBoxF1.isSelected()) {
                        this.jCheckBoxF1.setSelected(false);
                    } else {
                        this.jCheckBoxF1.setSelected(true);
                    }
                    break;
                //F2
                case 113:
                    if (this.jCheckBoxF2.isSelected()) {
                        this.jCheckBoxF2.setSelected(false);
                    } else {
                        this.jCheckBoxF2.setSelected(true);
                    }
                    break;
                //F3
                case 114:
                    if (this.jCheckBoxF3.isSelected()) {
                        this.jCheckBoxF3.setSelected(false);
                    } else {
                        this.jCheckBoxF3.setSelected(true);
                    }
                    break;
                //F4
                case 115:
                    if (this.jCheckBoxF4.isSelected()) {
                        this.jCheckBoxF4.setSelected(false);
                    } else {
                        this.jCheckBoxF4.setSelected(true);
                    }
                    break;
                //F5
                case 116:
                    if (this.jCheckBoxF5.isSelected()) {
                        this.jCheckBoxF5.setSelected(false);
                    } else {
                        this.jCheckBoxF5.setSelected(true);
                    }
                    break;
                //F6
                case 117:
                    if (this.jCheckBoxF6.isSelected()) {
                        this.jCheckBoxF6.setSelected(false);
                    } else {
                        this.jCheckBoxF6.setSelected(true);
                    }
                    break;
                //F7
                case 118:
                    if (this.jCheckBoxF7.isSelected()) {
                        this.jCheckBoxF7.setSelected(false);
                    } else {
                        this.jCheckBoxF7.setSelected(true);
                    }
                    break;
                //F8
                case 119:
                    if (this.jCheckBoxF3.isSelected()) {
                        this.jCheckBoxF3.setSelected(false);
                    } else {
                        this.jCheckBoxF3.setSelected(true);
                    }
                    break;
                //F9
                case 120:
                    if (this.jCheckBoxF9.isSelected()) {
                        this.jCheckBoxF9.setSelected(false);
                    } else {
                        this.jCheckBoxF9.setSelected(true);
                    }
                    break;
                //F10
                case 121:
                    if (this.jCheckBoxF10.isSelected()) {
                        this.jCheckBoxF10.setSelected(false);
                    } else {
                        this.jCheckBoxF10.setSelected(true);
                    }
                    break;
                //F11
                case 122:
                    if (this.jCheckBoxF11.isSelected()) {
                        this.jCheckBoxF11.setSelected(false);
                    } else {
                        this.jCheckBoxF11.setSelected(true);
                    }
                    break;
                //F12
                case 123:
                    if (this.jCheckBoxF12.isSelected()) {
                        this.jCheckBoxF12.setSelected(false);
                    } else {
                        this.jCheckBoxF12.setSelected(true);
                    }
                    break;
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    @Override
    public void componentAdded(ContainerEvent e) {

    }

    @Override
    public void componentRemoved(ContainerEvent e) {

    }
}
